training:
  project: "disco-ball"
  max_steps: 100000
  batch_size: 64 #64 before
  lr: 5e-4
  weight_decay: 1e-4
  in_context: True

data:
  setting: "scarce"
  train_path: "/mnt/home/lserrano/disco-ball/datasets/train_${data.setting}.npz"
  val_path: "/mnt/home/lserrano/disco-ball/datasets/val_${data.setting}.npz"
  test_path: "/mnt/home/lserrano/disco-ball/datasets/test_${data.setting}.npz"
  sub_x: 1
  sub_t: 1
  n_input_frames: 16
  n_output_frames: 2

model:
  n_states: 1
  hidden_dim: 128
  theta_dim: 2
  patch_size: 8
  ndims: [1]
  groups: 1 
  processor_blocks: 4
  drop_path: 0.
  num_heads: 4
  bias_type: "rel"
  hpnn_head_hidden_dim: 128
  max_steps: 10
  atol: 1e-6
  rtol: 1e-5 
  use_adjoint: False
  decoder_use_bias: True

test:
  #ckpt_time: "2025-06-15/23-50-46"
  ckpt_time: "2025-06-15/23-50-46"
  ckpt_path: "outputs/${test.ckpt_time}/model_final.ckpt"
  #ckpt_path: "outputs/2025-06-15/23-46-48/model_final.ckpt"
  dataset_name: "advection_diffusion"
  data_dir: "datasets"
  setting: "dense"  # or "scarce"
  n_input: 16
  n_pred: 50
  results_dir: "results/${test.ckpt_time}/"
  splits: ["train", "val", "test"]
